### PR TITLE
V1.39

### PR DESCRIPTION
**Pull request by hmaarrfk**
- closes https://github.com/conda-forge/grpcio-feedstock/pull/47
- closes https://github.com/conda-forge/grpcio-feedstock/pull/51
- closes https://github.com/conda-forge/grpcio-feedstock/pull/54

needed for: https://github.com/conda-forge/tensorflow-feedstock/pull/139
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
hmm comment: 
https://github.com/conda-forge/grpcio-feedstock/pull/46#issuecomment-901168596

indicates that we should look into `-lpthreads`

**Comment by hmaarrfk** [comment]
@xhochy any clue why osx is so slow...

**Comment by hmaarrfk** [comment]
:)

**Comment by ocefpaf** [comment]
LGTM but @bollwyvl definitely has more experience than me packaging this one.

**Review by ocefpaf — APPROVED** [review]

**Pull request merged**
