### PR TITLE
1.27.2

### PR DESCRIPTION
**Pull request by jjhelmus**
Update to version 1.27.2.  Pull in changes from AnacondaRecipes.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by jjhelmus** [comment]
Windows and Linux are working.  macOS is failing. :cry: .  This works on our build machines at Anaconda but the macOS configuration is a bit different than Azure.  
If anyone wants work on this feel free.

**Comment by hadim** [comment]
Could we merge this? It's better to have an updated package for Linux and Windows and not OSX than no updated package at all no?

**Comment by hadim** [comment]
I thought it was blocking for https://github.com/conda-forge/tensorboard-feedstock/pull/37#issuecomment-596102075 but it looks like `default` is available within `conda-forge` builds so the build passes.

**Comment by hadim** [comment]
@jjhelmus would you mind reviewing https://github.com/conda-forge/tensorboard-feedstock/pull/37 ?

**Comment by m-novikov** [comment]
> Windows and Linux are working. macOS is failing. cry . This works on our build machines at Anaconda but the macOS configuration is a bit different than Azure.
> If anyone wants work on this feel free.

Maybe this advice can help solve macos issue on azure https://github.com/PointCloudLibrary/pcl/issues/2601#issuecomment-557445280

**Comment by jschueller** [comment]
@ocefpaf the remaing PRs can be closed

**Comment by ocefpaf** [comment]
Done in #19 

Thanks @jjhelmus and @jschueller!

**Pull request closed without merging**
