### PR TITLE
Bump to version 1.23.0

### PR DESCRIPTION
**Pull request by mattgodbolt**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattgodbolt** [comment]
@conda-forge-admin, please rerender

**Comment by mattgodbolt** [comment]
I'm not sure how to ping conda-forge/core -- anyone able to help?

**Comment by jcrist** [comment]
@conda-forge/core

**Comment by CJ-Wright** [comment]
@conda-forge-admin, please rerender

**Comment by mattgodbolt** [comment]
Thanks both: doesn't seem to have worked, but appreciate the help! As a very rare visitor to the python world, I was super impressed with the setup you have here for conda packaging! Nice work!

**Comment by mattgodbolt** [comment]
@conda-forge-admin, please rerender

**Comment by mattgodbolt** [comment]
(trying again on the basis of it might work this time)

**Comment by mattgodbolt** [comment]
Ooh I see it was re-rendered already! Thanks all: hopefully this can be merged now!

**Pull request merged**
